services:
  freecad:
    build:
      context: .
      dockerfile: Dockerfile # The path to our Dockerfile
    container_name: freecad
    environment:
      - DISPLAY=${DISPLAY} # Connecting host and container GUI
      #- QT_X11_NO_MITSHM=1
      #- XDG_RUNTIME_DIR=/tmp/runtime-freecad
    #command: freecad --single-instance --pass --no-sandbox
    tty: true
    #privileged: true
    volumes:
      - ../:/workspace:cached # Workspace folder
      - /tmp/.X11-unix:/tmp/.X11-unix # Connecting host and container GUI
